name: Deploy Lambda to S3

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "Server/**" # Trigger only if server folder changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"
      S3_BUCKET: "tanseer-github-actions-test-s3-bucket"
      LAMBDA_FUNCTION: "tanseer-test-githubaction-lambda"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip the Server Folder
        run: |
          cd Server
          zip -r ../lambda_function.zip .

      - name: Upload New Zip to S3
        run: aws s3 cp lambda_function.zip s3://$S3_BUCKET/lambda_function.zip

      - name: Update Lambda Function Code
        run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION --s3-bucket $S3_BUCKET --s3-key lambda_function.zip