name: Deploy Lambda to S3

on:
  push:
    branches:
      - main
    paths:
      - "Server/**"  # Trigger only if server folder changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Delete Previous Zip from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          S3_BUCKET: "tanseer-github-actions-test-s3-bucket"
        run: aws s3 rm s3://$S3_BUCKET/lambda_function.zip || echo "No previous zip found, continuing..."

      - name: Zip the Server Folder
        run: |
          cd Server
          zip -r ../lambda_function.zip .  
          cd ..

      - name: Upload New Zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          S3_BUCKET: "tanseer-github-actions-test-s3-bucket"
        run: aws s3 cp lambda_function.zip s3://$S3_BUCKET/lambda_function.zip

      - name: Update Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          S3_BUCKET: "tanseer-github-actions-test-s3-bucket"
        run: aws lambda update-function-code --function-name tanseer-test-githubaction-lambda --s3-bucket $S3_BUCKET --s3-key lambda_function.zip